---

- name: PRE-DEPLOYMENT SETUP AND VALIDATION
  hosts: apic


  tasks:

    # All of these should be defined:
    # ansible_host, ansible_port, ansible_user, ansible_password, validate_certs
    # customer_name
    - name: Test that connection details are defined
      assert:
        that:
          - "ansible_host is defined"
          - "ansible_port is defined"
          - "ansible_user is defined"
          - "ansible_password is defined"
          - "validate_certs is defined"
          - "customer_name is defined"
        fail_msg: "Please ensure that these variables exist: ansible_host,
          ansible_port, ansible_user, ansible_password, validate_certs
          and customer_name!"
        quiet: true

    # These variables represent the data model and are used by
    # the rest of the playbook to deploy the policy.
    - name: Load Infrastructure Definition
      include_vars:
        file: "{{ customer_name }}.yml"

- name: CREATE APPLICATION PROFILES AND EPGS
  hosts: apic

  tasks:

    - name: Create Application Profile
      aci_ap:
        host: "{{ ansible_host }}"
        port: "{{ ansible_port }}"
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        validate_certs: "{{ validate_certs }}"

        tenant: "{{ tenant.name }}"
        ap: "{{ item.name }}"
        description: "{{ item.description }}"
        state: present
      loop: "{{ tenant.apps }}"



      # ADD MODULE PARAMETERS HERE!
      delegate_to: localhost

    - name: Create EPG
      aci_epg:
        host: "{{ ansible_host }}"
        port: "{{ ansible_port }}"
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        validate_certs: "{{ validate_certs }}"

        tenant: "{{ tenant.name }}"
        bd: "{{ item.bd }}"
        ap: "{{ item.ap }}"
        epg: "{{ item.name }}"
        description: "{{ item.description }}"
        state: present
      loop: "{{ tenant.epgs }}"




      # ADD MODULE PARAMETERS HERE!
      delegate_to: localhost

    - name: Connect EPG to Domain
      aci_epg_to_domain:
        host: "{{ ansible_host }}"
        port: "{{ ansible_port }}"
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        validate_certs: "{{ validate_certs }}"

        tenant: "{{ tenant.name }}"
        ap: "{{ item.ap }}"
        epg: "{{ item.name }}"
        domain: "{{ item.domain }}"
        domain_type: "{{ domains[item.domain].domain_type}} "
        vm_provider: "{{ domains[item.domain].vm_provider}} "
        state: present
      delegate_to: localhost
      loop: "{{ tenant.epgs }}"

      # ADD MODULE PARAMETERS HERE!
      
